Components logging
MakarenkoAI/sc-component-manager pull request #3
Opened 2024-03-27 18:12 UTC by MakarenkoAI

* [ ] Update changelog if needed
* [ ] Update SCn documentation if needed

depends on https://github.com/MksmOrlov/ostis-kb-lib/tree/test

2024-04-01 13:02 UTC, MksmOrlov requested changes
I tried to install cat and got debug that already have it. By I don't

2024-04-01 13:02 UTC, MksmOrlov commented on src/manager/agents/common-module/module/keynodes/ScComponentManagerKeynodes.cpp
> +ScAddr ScComponentManagerKeynodes::subsystems_set;
```suggestion
ScAddr ScComponentManagerKeynodes::consept_subsystems_set;
```

2024-04-01 13:02 UTC, MksmOrlov commented on src/manager/agents/common-module/module/keynodes/ScComponentManagerKeynodes.cpp
> +ScAddr ScComponentManagerKeynodes::ostis_system_knowledge_base;
```suggestion
ScAddr ScComponentManagerKeynodes::sc_model_of_knowledge_base;
```

2024-04-01 13:02 UTC, MksmOrlov commented on kb/system_components.gwf
Remove this file. You should create this structure in code and check if it exists before creation. Make this resolve one time when manager starts

2024-04-01 13:02 UTC, MksmOrlov commented on src/manager/agents/init-module/utils/sc_component_manager_command_init.cpp
> +      SC_LOG_DEBUG("Component \"" + context->HelperGetSystemIdtf(component) + "\" is already installed");
```suggestion
      SC_LOG_DEBUG("Component \"" << context->HelperGetSystemIdtf(component) << "\" is already installed");
```
Use only << to concat in SC_LOG macros. Check everywhere

2024-04-01 13:02 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +        keynodes::ScComponentManagerKeynodes::subsystems_set}};
use map instead of vector

2024-04-01 13:02 UTC, MksmOrlov commented on kb/system_components.gwf
You can make scs file with template (structure with variables) and find it by system identifier in code and then build and generate by template

2024-04-01 13:02 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +      continue;
странная логика. Если не нашли декомпозицию майселфа, то идем ещё раз по циклу классов компонента и ищем опять? Но действия в цикле не влияют на это условие. В общем look at the gwf comment and remove this logic from cycle

2024-04-01 13:02 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +  {
This cycle is sooo strange. Why do you iterate over classes

2024-04-01 13:02 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +ScAddr CommonUtils::GetAddrComponentOfMyself(ScMemoryContext & m_memoryCtx, ScAddr const & component)
addr component is not correct for English grammar. And as I see you return decomposition, not component or myself

2024-04-01 13:02 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +  SC_LOG_DEBUG(m_memoryCtx.HelperGetSystemIdtf(specification));
this debug shouldn't be inside this method

2024-04-01 13:02 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +    }
We must find it onlly by rrel_key_sc_element quintuple. No need to iterate over the all specification. If there is no rrel_key_sc_element from specification to its component in all our specifications, add them.
Check sc-web, ims specifications and from MksmOrlov (cat and ostis-ui-lib). Check all our repos with specification please

2024-04-01 13:16 UTC, MksmOrlov commented on kb/system_components.gwf
Rename nrel_decomposition from myself to nrel_ostis_system_decomposition

2024-04-01 13:19 UTC, MksmOrlov commented on kb/system_components.gwf
User interface is subsystem

2024-04-07 18:06 UTC, MakarenkoAI commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +        keynodes::ScComponentManagerKeynodes::subsystems_set}};
https://stackoverflow.com/questions/37301160/invalid-operands-to-binary-expression-const-and-const get this issue

2024-04-07 18:12 UTC, MakarenkoAI commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +    }
https://github.com/MksmOrlov/ostis-kb-lib/tree/test

2024-04-07 18:14 UTC, MakarenkoAI commented on kb/system_components.gwf
in main.cpp?

2024-04-14 10:18 UTC, closed without merging